services:
  ner-leaderboard:
    image: ner-leaderboard
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:8501"

    volumes:
      - /projects/text-classification-leaderboard-app/DATA/

    environment:
      TESTSETS_PATH: /mounted/testsets
      DB_PATH: /mounted/submissions.db
      USER_CONFIG_PATH: /mounted/users_config.yaml
      SUBMISSION_SAVE_PATH: /mounted/saved_submissions

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8501"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

    labels:
      maintainer: "wesam.alnabki@gmail.com"
      service: "NER Leaderboard"
